version: "3.6"

services:

  database:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file:
      - ./docker/config/database.env
    volumes: 
      - db-data:/data/db
    ports:
      - 27017:27017
    networks:
      - web

  app:
    build: .
    command: python app.py
    env_file:
      - ./docker/config/app.env
    volumes:
      - ./src:/src
    ports:
      - 9000:9000
    depends_on:
      - database
    networks:
      - web
    restart: on-failure

networks:
  web:
    driver: bridge
  
volumes:
  db-data:
