version: "3.6"

services:

  database:
    image: mongo:5.0.2
    command: mongod --port $MONGODB_INTERNAL_PORT
    restart: unless-stopped
    env_file:
      - ./docker/config/database.env
    volumes: 
      - db-data:/data/db
    ports:
      - $MONGODB_INTERNAL_PORT
    networks:
      - web

  app:
    build: .
    command: python app.py
    env_file:
      - ./docker/config/app.env
    volumes:
      - ./src:/src
    ports:
      - $APP_EXPOSED_PORT:$APP_INTERNAL_PORT
    depends_on:
      - database
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    driver: bridge
  
volumes:
  db-data:
